import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AiResponseProvider } from "./Context/AiResponseContext";
import {PageConfigProvider} from "./Context/pageConfigContext"
import { PageSelectionProvider } from "./Context/ActivePageContext";
import { ComponentPageConfigProvider } from "./Context/ComponentPageContext";
import { BlankPageProvider } from "./Context/BlankPageContext";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "@/components/ui/toaster";
import { CustomPromptProvider } from "./Context/CustomPromptContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <BlankPageProvider>
      <PageConfigProvider>
        <AiResponseProvider>
          <PageSelectionProvider>
            <ComponentPageConfigProvider>
            <CustomPromptProvider>
              <body className={inter.className}>
                <div className="max-w-7xl mx-auto">
                  <Navbar />
                  <svg
className='absolute inset-0 -z-10 h-full w-full stroke-gray-200 [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]'
aria-hidden='true'>
<defs>
    <pattern
    id='0787a7c5-978c-4f66-83c7-11c213f99cb7'
    width={200}
    height={200}
    x='50%'
    y={-1}
    patternUnits='userSpaceOnUse'>
    <path d='M.5 200V.5H200' fill='none' />
    </pattern>
</defs>
<rect
    width='100%'
    height='100%'
    strokeWidth={0}
    fill='url(#0787a7c5-978c-4f66-83c7-11c213f99cb7)'
/>
</svg>
                  {children}
                  <Toaster />
                </div>
              </body>
              </CustomPromptProvider>
            </ComponentPageConfigProvider>
          </PageSelectionProvider>
        </AiResponseProvider>
      </PageConfigProvider>
      </BlankPageProvider>
    </html>
    </ClerkProvider>
  );
}
