import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AiResponseProvider } from "./Context/AiResponseContext";
import {PageConfigProvider} from "./Context/pageConfigContext"
import { PageSelectionProvider } from "./Context/ActivePageContext";
import { ComponentPageConfigProvider } from "./Context/ComponentPageContext";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PageConfigProvider>
        <AiResponseProvider>
          <PageSelectionProvider>
            <ComponentPageConfigProvider>
              <body className={inter.className}>
                <div className="max-w-7xl mx-auto">
                  <Navbar />
                  {children}
                </div>
              </body>
            </ComponentPageConfigProvider>
          </PageSelectionProvider>
        </AiResponseProvider>
      </PageConfigProvider>
    </html>
  );
}
