import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AiResponseProvider } from "./Context/AiResponseContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AiResponseProvider>
        <body className={inter.className}>
          <div className="max-w-7xl mx-auto">
            <Navbar />
            {children}</div></body>
      </AiResponseProvider>
    </html>
  );
}
